### ISSUE TITLE
Fridge Door Will Not Close

### ISSUE THREAD

**Issue by Ungari** [MidnightGH/VTOL_SUPREMACY-#7]
I can only open the door of Mini-Fridge, but not close it.
How am I supposed to keep my food and beverages cold?
This is simply another example of the unacceptable FAIL CASCADE that is littered all over this file.

**Comment by MidnightGH** [comment]
Actually,
there is a bug with the AddAction command and condition statements.
Repeatedly adding the action, and refusing to delete the action after being used.
I'm closing this.
